# Generated by Django 2.2.6 on 2021-01-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210118_1009'),
        ('account', '0002_auto_20210113_1051'),
    ]

    operations = [
    ]
