# Generated by Django 2.2 on 2021-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210113_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='uomcategory',
            name='name',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Waiting for apprave', 'Waiting for apprave'), ('Not approved', 'Not approved')], max_length=100, null=True),
        ),
    ]
