# Generated by Django 2.2 on 2020-09-16 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200908_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom', to='inventory.Uom'),
        ),
    ]
