# Generated by Django 2.2 on 2020-10-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201012_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
