# Generated by Django 2.2 on 2021-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210114_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uomcategory',
            name='name',
            field=models.CharField(default='uh', max_length=30),
            preserve_default=False,
        ),
    ]
