# Generated by Django 2.2 on 2020-10-12 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0005_auto_20200908_1635'),
        ('account', '0002_auto_20201012_1717'),
        ('location', '0001_initial'),
        ('inventory', '0002_auto_20201012_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransaction1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(help_text='code number of a transaction', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction1_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction1_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=10)),
                ('global_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('drafted', 'Drafted'), ('Partial_receive', 'Partially Received'), ('closed', 'Closed'), ('open', 'Open')], default='open', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('balance', models.IntegerField(default=0, help_text='The remaining quantities to be received')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', '%'), ('amount', 'EGP')], default='percentage', max_length=11)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, default='EGP', null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=10)),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('EGP', 'EGP E£'), ('EUR', 'EUR €'), ('USD', 'USD $')], default='EGP', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EGP', max_digits=14)),
                ('status', models.CharField(choices=[('received', 'Received'), ('returned', 'Returned'), ('shipping', 'Shipping')], default='drafted', max_length=8)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_per_unit_currency', djmoney.models.fields.CurrencyField(choices=[('EGP', 'EGP E£'), ('EUR', 'EUR €'), ('USD', 'USD $')], default='EGP', editable=False, max_length=3)),
                ('price_per_unit', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EGP', max_digits=14, null=True)),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('EGP', 'EGP E£'), ('EUR', 'EUR €'), ('USD', 'USD $')], default='EGP', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EGP', max_digits=14)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_transaction_created_by', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SalesOrder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=8)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('balance', models.IntegerField(blank=True, help_text='The remaining quantities to be received for this item', null=True)),
                ('last_updated_at', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_transation_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, default='EGP', null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PurchaseOder')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransactionLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=4)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_created_by', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('material_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.MaterialTransaction1')),
            ],
        ),
        migrations.AddField(
            model_name='materialtransaction1',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.PurchaseOder'),
        ),
        migrations.AddField(
            model_name='materialtransaction1',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.SalesOrder'),
        ),
        migrations.AddField(
            model_name='materialtransaction1',
            name='stoke_take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.StokeTake'),
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(help_text='code number of a transaction', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=4)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_created_by', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.PurchaseOder')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.SalesOrder')),
                ('stoke_take', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.StokeTake')),
            ],
        ),
    ]
