# Generated by Django 2.2 on 2021-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='sale_code',
            field=models.CharField(blank=True, help_text='code number of a so', max_length=100, null=True, verbose_name='SO Number'),
        ),
    ]
