# Generated by Django 2.2.6 on 2021-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_purchaseoder_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoder',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
