# Generated by Django 2.2 on 2021-01-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210117_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='total_after_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
