# Generated by Django 2.2.6 on 2021-01-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchaseoder_supplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoder',
            name='supplier_code',
            field=models.CharField(blank=True, help_text='code number of a supplier', max_length=250, null=True),
        ),
    ]
