# Generated by Django 2.2.6 on 2021-01-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210114_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransactionlines',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'inbound'), ('out', 'outbound')], max_length=4),
        ),
    ]
