# Generated by Django 2.2 on 2020-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201013_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_balance',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='inventory_balance',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
