# Generated by Django 2.2.6 on 2021-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210114_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseoder',
            old_name='global_price',
            new_name='subtotal_price',
        ),
        migrations.AddField(
            model_name='purchaseoder',
            name='tax',
            field=models.DecimalField(decimal_places=3, default=0.14, max_digits=4),
            preserve_default=False,
        ),
    ]
