# Generated by Django 2.2 on 2021-01-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_salesorder_total_after_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_after_tax',
        ),
    ]
