# Generated by Django 2.2 on 2021-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210118_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
