# Generated by Django 2.2.6 on 2021-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210117_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoder',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
