# Generated by Django 2.2.6 on 2021-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_purchaseoder_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoder',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
