# Generated by Django 2.2 on 2021-01-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_salestransaction_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='discount_percentage',
        ),
    ]
