# Generated by Django 2.2 on 2021-01-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_salestransaction_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='currency',
        ),
    ]
