# Generated by Django 2.2.6 on 2021-01-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210119_0935'),
        ('orders', '0009_auto_20210119_1437'),
    ]

    operations = [
    ]
