# Generated by Django 2.2.6 on 2021-01-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_merge_20210119_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
