# Generated by Django 2.2.6 on 2021-01-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210120_1400'),
        ('orders', '0012_auto_20210125_0913'),
    ]

    operations = [
    ]
