# Generated by Django 2.2.6 on 2021-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210120_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='order_name',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='currency',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_so_number',
            field=models.CharField(blank=True, help_text='Customer SO number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_type',
            field=models.CharField(choices=[('percentage', '%'), ('amount', 'EGP')], default='percentage', max_length=11),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sale_code',
            field=models.CharField(blank=True, help_text='SO number', max_length=100, null=True, verbose_name='SO Number'),
        ),
    ]
