# Generated by Django 2.2.6 on 2021-01-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210125_1356'),
        ('orders', '0012_auto_20210125_0913'),
    ]

    operations = [
    ]
